#!/bin/bash

npm install adm-zip
npm install app-route
npm install archiver
npm install async
npm install aws-sdk
npm install basecamp
npm install bing-translate
npm install bluebird
npm install body-parser
npm install built
npm install built.io
npm install contextio
npm install cron-parser
npm install csvjson
npm install csvtojson
npm install deep-diff
npm install dynamics-crm-xrm
npm install edgegrid
npm install evernote
npm install express
npm install fb
npm install fs-extra
npm install ftp
npm install google-spreadsheet
npm install googleapis
npm install googleplaces
npm install hackpad
npm install hdb
npm install heroku-client
npm install html-to-text
npm install htmlencode
npm install htmlparser2
npm install ical-toolkit
npm install jade
npm install js2xmlparser
npm install json-2-csv
npm install json-stringify-safe
npm install jsonexport
npm install jwt-simple
npm install kue
npm install lodash
npm install mailchimp
npm install metalsmith
npm install metalsmith-collections
npm install metalsmith-layouts
npm install metalsmith-markdown
npm install metalsmith-permalinks
npm install metatags
npm install mime
npm install moment
npm install moment-timezone
npm install mongodb
npm install mssql
npm install netlify
npm install node-emoji
npm install node-gcm
npm install node-rfc
npm install node-twitter-api
npm install node-uuid
npm install nodemailer
npm install nodemailer-smtp-transport
npm install phantom
npm install pipedrive
npm install postmark
npm install pubnub
npm install q
npm install request
npm install rest
npm install sendgrid
npm install soap
npm install ssh2
npm install ssh2-sftp-client
npm install strong-soap
npm install surveymonkey
npm install turndown
npm install twitter
npm install underscore
npm install uuid
npm install w3cjs
npm install winston
npm install ws
npm install wssecurity-soap
npm install x12
npm install xlsjs
npm install xlsx
npm install xml2js

