#!/bin/bash

npm install @builtioflow/cliwrapper
npm install adm-zip
npm install app-router
npm install async
npm install aws-sdk
npm install bluebird
npm install body-parser
npm install connect-mongo
npm install contextio
npm install cookie-parser
npm install evernote
npm install express
npm install express-session
npm install fs-extra
npm install hackpad
npm install lodash
npm install moment
npm install mongoose
npm install node-rfc
npm install pluralize
npm install q
npm install ramda
npm install request
npm install soap
npm install twitter
npm install underscore
npm install winston
npm install xml2json
npm install chai
npm install chai-as-promised
npm install cloc
npm install istanbul
npm install mocha
npm install mocha-each
npm install mochawesome
npm install nock
npm install should
npm install supertest