#!/bin/bash

npm install @builtioflow/cliwrapper
npm install adm-zip
npm install bing-translate
npm install bluebird
npm install body-parser
npm install built.io
npm install crypto
npm install deepmerge
npm install edgegrid
npm install ejs
npm install evernote
npm install express
npm install fs-extra
npm install ftp
npm install get-files-in-dir
npm install hackpad
npm install hackpad
npm install jwt-simple
npm install lodash
npm install mailchimp
npm install mongodb
npm install mongoose
npm install mssql
npm install node-rfc
npm install pubnub
npm install querystring
npm install redis
npm install redis-sentinel
npm install request
npm install soap
npm install ssh2
npm install ssh2-sftp-client
npm install supertest
npm install syntax-error
npm install underscore
npm install winston
npm install wssecurity-soap
npm install xml2js
npm install cloc
npm install should