#!/bin/bash

npm install @builtioflow/flow-helper
npm install app-router
npm install async
npm install aws-sdk
npm install bcrypt
npm install bluebird
npm install body-parser
npm install built
npm install evernote
npm install express
npm install feed-read
npm install feedparser
npm install googleapis
npm install html-to-text
npm install jsonschema
npm install jwt-simple
npm install lodash
npm install mailchimp
npm install mailchimp-api-v3
npm install moment
npm install moment-timezone
npm install mongoose
npm install multer
npm install node-uuid
npm install pluralize
npm install q
npm install request
npm install self-addressed
npm install sendgrid
npm install setconfig
npm install surveymonkey
npm install twilio
npm install twitter
npm install underscore
npm install uuid
npm install winston
npm install xml2json
npm install chai
npm install chai-as-promised
npm install cloc
npm install get-files-in-dir
npm install mocha
npm install nock
npm install ramda
npm install should
npm install supertest
npm install syntax-error
